apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  selector:
    matchLabels:
      app: spring-boot-docker
  replicas: 2
  template:
    metadata:
      labels:
       app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: spring-boot-docker.jar
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080